import { api } from '@/lib/brooks-api';

export type AppNotificationType = 'warning' | 'success' | 'error' | 'info';

export interface AppNotification {
  id: string;
  title: string;
  message: string;
  type: AppNotificationType;
  created_at: string;
  source: 'backend' | 'low_stock' | 'invoice' | 'outsourced';
  read: boolean;
}

const READ_STORAGE_KEY = 'brooks.read_notification_ids.v1';

const normalizeList = (data: any): any[] => {
  if (Array.isArray(data)) return data;
  if (Array.isArray(data?.results)) return data.results;
  return [];
};

const toIsoDate = (value: string | null | undefined) => {
  const parsed = value ? new Date(value) : new Date();
  return Number.isNaN(parsed.getTime()) ? new Date().toISOString() : parsed.toISOString();
};

const loadReadIds = (): Set<string> => {
  if (typeof window === 'undefined') return new Set<string>();
  try {
    const raw = localStorage.getItem(READ_STORAGE_KEY);
    if (!raw) return new Set<string>();
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) return new Set<string>();
    return new Set(parsed.map((item) => String(item)));
  } catch {
    return new Set<string>();
  }
};

const saveReadIds = (ids: Set<string>) => {
  if (typeof window === 'undefined') return;
  localStorage.setItem(READ_STORAGE_KEY, JSON.stringify(Array.from(ids)));
};

const mapBackendType = (notification: any): AppNotificationType => {
  const raw = String(
    notification?.type || notification?.notification_type || notification?.level || 'info'
  ).toLowerCase();

  if (raw.includes('error') || raw.includes('failed')) return 'error';
  if (raw.includes('warning') || raw.includes('overdue') || raw.includes('reminder')) return 'warning';
  if (raw.includes('success')) return 'success';
  return 'info';
};

export const fetchNotificationsFeed = async (): Promise<AppNotification[]> => {
  const readIds = loadReadIds();

  const [logsResult, inventoryResult, invoicesResult, outsourcedResult] = await Promise.allSettled([
    api.notifications.list(),
    api.inventory.list(),
    api.invoices.list(),
    api.outsourcedServices.unpaid(),
  ]);

  const feed: AppNotification[] = [];

  if (logsResult.status === 'fulfilled') {
    const logs = normalizeList(logsResult.value);
    logs.forEach((log: any) => {
      const id = `backend-${log.id}`;
      feed.push({
        id,
        title: String(log.subject || log.notification_type_display || 'System Notification'),
        message: String(log.message || 'Notification generated by the system.'),
        type: mapBackendType(log),
        created_at: toIsoDate(log.sent_at || log.created_at),
        source: 'backend',
        read: readIds.has(id),
      });
    });
  }

  if (inventoryResult.status === 'fulfilled') {
    const inventory = normalizeList(inventoryResult.value);
    inventory
      .filter((item: any) => {
        if (typeof item?.is_low_stock === 'boolean') return item.is_low_stock;
        const stock = Number(item?.stock_quantity || 0);
        const threshold = Number(item?.low_stock_threshold || 0);
        return stock <= threshold;
      })
      .forEach((item: any) => {
        const id = `low-stock-${item.id}`;
        feed.push({
          id,
          title: `Low stock: ${item.name || 'Inventory Item'}`,
          message: `${Number(item?.stock_quantity || 0)} left (minimum ${Number(item?.low_stock_threshold || 0)}).`,
          type: 'warning',
          created_at: toIsoDate(item.updated_at || item.created_at),
          source: 'low_stock',
          read: readIds.has(id),
        });
      });
  }

  if (invoicesResult.status === 'fulfilled') {
    const invoices = normalizeList(invoicesResult.value);
    const today = new Date();
    invoices
      .filter((invoice: any) => {
        const status = String(invoice?.status || '').toLowerCase();
        if (status === 'overdue') return true;
        if (status === 'paid' || status === 'dispatched') return false;
        if (!invoice?.due_date) return false;
        const dueDate = new Date(invoice.due_date);
        if (Number.isNaN(dueDate.getTime())) return false;
        return dueDate < today;
      })
      .forEach((invoice: any) => {
        const id = `invoice-overdue-${invoice.id}`;
        feed.push({
          id,
          title: `Invoice overdue: ${invoice.invoice_number || invoice.id}`,
          message: `${invoice.customer_name || 'Customer'} has an overdue balance of ${invoice.total_amount || 0}.`,
          type: 'warning',
          created_at: toIsoDate(invoice.updated_at || invoice.created_at || invoice.due_date),
          source: 'invoice',
          read: readIds.has(id),
        });
      });
  }

  if (outsourcedResult.status === 'fulfilled') {
    const services = normalizeList(outsourcedResult.value);
    services.forEach((service: any) => {
      const id = `outsourced-unpaid-${service.id}`;
      const totalCost = Number(service?.labor_cost || 0) + Number(service?.parts_cost || 0);
      feed.push({
        id,
        title: `Unpaid outsourced service: ${service.service_name || 'Service'}`,
        message: `Vendor ${service.vendor_name || service.vendor_company_name || 'N/A'} has ${totalCost} outstanding.`,
        type: 'warning',
        created_at: toIsoDate(service.updated_at || service.created_at),
        source: 'outsourced',
        read: readIds.has(id),
      });
    });
  }

  const deduped = new Map<string, AppNotification>();
  feed.forEach((item) => {
    if (!deduped.has(item.id)) {
      deduped.set(item.id, item);
    }
  });

  return Array.from(deduped.values()).sort((a, b) => {
    return new Date(b.created_at).getTime() - new Date(a.created_at).getTime();
  });
};

export const markNotificationRead = (id: string) => {
  const readIds = loadReadIds();
  readIds.add(id);
  saveReadIds(readIds);
};

export const markNotificationsRead = (ids: string[]) => {
  const readIds = loadReadIds();
  ids.forEach((id) => readIds.add(id));
  saveReadIds(readIds);
};

export const getUnreadNotificationCount = async (): Promise<number> => {
  const feed = await fetchNotificationsFeed();
  return feed.filter((item) => !item.read).length;
};
